version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: nechat-app-${POSTGRES_DB}
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
